### ISSUE TITLE
Error with make install

### ISSUE THREAD

**Issue by temuller** [cschreib/fastpp#16] opened 2022-07-11 14:11 UTC
Hi,

I am trying to install fast++, but I am getting an error (see below). I have a Dell XPS15 with Ubuntu 22.04 OS. I also installed `cmake` with `sudo apt install cmake`.

Error:
```
...
[ 81%] Performing build step for 'fast++'
[  7%] Building CXX object CMakeFiles/fast++.dir/fast++-read_input.cpp.o
In file included from /home/tomas/fastpp/external/include/vif/core/vec.hpp:1236,
                 from /home/tomas/fastpp/src/fast++.hpp:5,
                 from /home/tomas/fastpp/src/fast++-read_input.cpp:1:
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:15: error: invalid use of incomplete type ‘struct vif::impl::op_mul_t’
  155 |     VECTORIZE(*, *=)
      |               ^
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:26:56: note: in definition of macro ‘OP_TYPE’
   26 |         #define OP_TYPE(op) decltype(impl::op_node_t{} op impl::op_node_t{})
      |                                                        ^~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:5: note: in expansion of macro ‘VECTORIZE’
  155 |     VECTORIZE(*, *=)
      |     ^~~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:12:16: note: forward declaration of ‘struct vif::impl::op_mul_t’
   12 |         struct op_mul_t;
      |                ^~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:78:56: error: template argument 1 is invalid
   78 |         vec<Dim,typename impl::op_res_t<OP_TYPE(op),T,U>::type> operator op (const vec<Dim,T>& v, const vec<Dim,U>& u) { \
      |                                                        ^
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:5: note: in expansion of macro ‘VECTORIZE’
  155 |     VECTORIZE(*, *=)
      |     ^~~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:78:57: error: ‘<declaration error>’ is not a template [-fpermissive]
   78 |         vec<Dim,typename impl::op_res_t<OP_TYPE(op),T,U>::type> operator op (const vec<Dim,T>& v, const vec<Dim,U>& u) { \
      |                                                         ^~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:5: note: in expansion of macro ‘VECTORIZE’
  155 |     VECTORIZE(*, *=)
      |     ^~~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:78:63: error: template argument 2 is invalid
   78 |         vec<Dim,typename impl::op_res_t<OP_TYPE(op),T,U>::type> operator op (const vec<Dim,T>& v, const vec<Dim,U>& u) { \
      |                                                               ^
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:5: note: in expansion of macro ‘VECTORIZE’
  155 |     VECTORIZE(*, *=)
      |     ^~~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp: In function ‘int vif::operator*(const vif::vec<Dim, Type>&, const vif::vec<Dim, U>&)’:
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:15: error: invalid use of incomplete type ‘struct vif::impl::op_mul_t’
  155 |     VECTORIZE(*, *=)
      |               ^
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:26:56: note: in definition of macro ‘OP_TYPE’
   26 |         #define OP_TYPE(op) decltype(impl::op_node_t{} op impl::op_node_t{})
      |                                                        ^~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:155:5: note: in expansion of macro ‘VECTORIZE’
  155 |     VECTORIZE(*, *=)
      |     ^~~~~~~~~
/home/tomas/fastpp/external/include/vif/core/bits/operators.hpp:12:16: note: forward declaration of ‘struct vif::impl::op_mul_t’
   12 |         struct op_mul_t;
      |                ^~~~~~~~
compilation terminated due to -fmax-errors=5.
make[5]: *** [CMakeFiles/fast++.dir/build.make:76: CMakeFiles/fast++.dir/fast++-read_input.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:87: CMakeFiles/fast++.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/fast++.dir/build.make:86: fast++-prefix/src/fast++-stamp/fast++-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:168: CMakeFiles/fast++.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by cschreib** [comment] 2022-07-11 19:01
Hi Tomás, and thank you for the bug report. I have not been able to reproduce this on a fresh install of Ubuntu 22.04. Would you mind copying the full terminal output you get when running `cmake`, please? In particular, am I interested in the line that reads
```
-- The CXX compiler identification is GNU x.y.z
```
so I can see more precisely which compiler version you are using. If you can also include the output of the command `c++ --version`, that can help me further.

**Comment by temuller** [comment] 2022-07-12 06:34
This is the output of `c++ --version`:
```
c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I already ran `cmake` (successfully), so I don't get the expected output. However, `cmake --version` gives:
```
cmake version 3.22.1
```

**Comment by cschreib** [comment] 2022-07-12 07:11
Thanks! Regarding `cmake`, could you try to run it again from the start, in a new build folder, so you can get the full output again?

**Comment by temuller** [comment] 2022-07-12 07:38
Ok, I am re-installing it from scratch and I get:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected (-DCMAKE_BUILD_TYPE=...)
-- Default to Release.
-- No install directory selected (-DCMAKE_INSTALL_PREFIX=...)
-- Default to /home/tomas/fastpp/bin
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomas/fastpp/build
```

**Comment by cschreib** [comment] 2022-07-12 08:10
Thank you. I have been able to reproduce this error in [Compiler Explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEjaSuADJ4DJgAcj4ARpjEIADs0gAOqAqETgwe3r7%2BpClpjgIhYZEsMXGJtpj2hQxCBEzEBFk%2BflwBdpgOGfWNBMUR0bEJ0goNTS057bbj/aGDZcOJAJS2qF7EyOwc5gDMocjeWADUJrtutHgshApn2CYaAIJ7B0eYp%2BdOY8SYrHcPzzM%2BwYhy8JzObmQY3wgn%2BTxeILeHzcADcukRiHDAcDQeDzmJgCRCAgWFiAcw2AokkwtscUXgqKd4lYnsc2ccAPRc7k83l8/kCgUA9mcjki8USgDySViTAxCglivZXOFysF6o1mo5ANVbIImBYSQM%2Boh0JAIDSAC9MAB9AjHcKkY4EACeMop7wAKliRd8vA46V0mVZ4gARM4s56stXHACycoQBrleFEtGOqBlxDlJFu0bZHqpNPeVyNwd14r9AYzNpYXlodoj5d9BGI/vt1fwKIbu0jSsr7aSNYw3d7iv76cHTHQ6BHTfZ4%2BrCi8UVn8LzFZbbYnNoYGFt9pMzLnEurtfrA9lGOOACpjhBq7usHblo310qO3guxes1exffB4%2B%2B4vj2x7iqew7ftmxCnGYACsd4Pnuz6vo8SoitWU4zpBV7WAhAFIQQwGjmh25Liu2EkMcAC0eE7gRRGgYe4YgWuqGKnsWA0GExySsoNqegAmso2D/ssxxYIcroyhAJa0OaiFPgQh4hqGE7HLJ8n4YpylMS%2BrFKvqhrGpgEJSYwrBej6ipeGkRjHCwCY2lETAANb7m67xnKp3osVGbESoZRpyiZ5xmR6PHKE6YUWccnpRR54VyFZEoLoOPwKKufkGQaQUmqFCUxXFzoFWwxxJbs9xvvOm5VmlmAZUp5ynnWdpOkV5XYGWVUSjZoTAMVMofKp0WlWaIASUwLoQhJtBmRAY0zSiYgQg5BAIE5rnuTKEI%2BfcFUQGJ16gX2BDoOai3Lecq3rc5bl2h5EIdXcB3Adg5pmShSpMShoGBcZpklV68XujFT3dccqU2ul3YeIOnatbFTodV1/lob1dlmUNA3maNp3nV0k3TV0s0efNePjcTS20Ctjm3VtIVuLtz1idq4MnWdFOHFTNNrRtd0fecT37csr3vQ9vlfWGP3g39wUAyDpVFSN7xg6jzatrVUP1TD4FYW1SN3CjJFsuj/WY152PhQtBNTecM1zdbXOXW4118/TO3/MLMGwcdY7kxd1NXbTm33dtgueyJIt3GLYfEeK32%2Bb9OX/flCtA5boPJRuGsDlrDUQhh04I%2B1hs6Wz7Km9jWPKxD/s20Tkmk47tDc0HvN06HDNM171i%2BylddO4HLvB/z4tuELkeiyAAtxyKCeRknRly6nOPpzXqsnTn27Q41sM2mRxcGxVRvG5X5u7MNgO1xzE22249tNwPLfO67HcC4zEcHdRfcbjflMvyPd24cKrMynjPRiUsJbsm%2BvpaBQJOLzGOAANWwIzSUAAlAAkgALREhmJ0CgMxiRMLBNwi9coMzGlafcxxQxXGBqvRGGdSrIxIWQ8GaJTDnDoSwUgNcNIgGrDvCEvF%2BJCTwUkVYcUOoxxCp1DMl5KIZjvGgBgYxAxcLcDw0gTMzAADY6ROlUeozhEJtFPX0ccLwxDmSnFIT/H4BANgMDLJAiwdj2Fq2gVLWBbIUFoKwbgiA14nRHQvnpVG/jPQYJwSJawTpe7hPLFEmJQSOROm1Ek9cKTAlxLggkuCXkIkihybEiAVEnRUSKTqdcewvAME4sg1B0Tck6h8X5UI9oHKhC/jpMMHBVhyQ4LBXgfgOBaFIKgTgZDLC4UIRsWkeweB8M0AM1YLkQCwQ0AAOg0Po9oABOPReiNCwUSJILg%2BhOCSFGasyZnBeAKBAAEAgqzVhwFgDARAKBUCGjoLEcglA0B/PoHEYAXAuBmD4HQfUxAnkQCiHcqIoRGguk4Ms4FbBBCSgYLQNF4zeBYAckYcQBLSD4B%2BN0NETyyWYFUF0Lw%2Bo7mdOqHcy4UQszEBdB4LAdyWxXHRQMvgBhgAKCQXgTAAB3aUjBBUyEECIMQ7ApDyvkEoNQdzdCXIMEYFAvdLD6DwFEJ5kBVgZlqDSqikpdjUWhF5UwszLAQuoqGcIoZsAWDkAAcXZFRAA6mIWgjzqjogyC4Bpkw2iBAaQMUo5Q9D5HSAISNCbUhJoYLGoYcRLmdG6AIXoExPCtD0Lm2oBa5glCzSW2YKac2zEzYsbNqx5mbGVXwn42weCDM4CM0gYyJlTI4KoAAHHoqiejJDHGAMgZAxwIXbLMHeGZVgDXHFwIQSiSynQeBBbEGCuwuDLF4K8glItSAbK2VcjgNzSAsE2QEftvBB2POeSs09pAPnfPWAQJIjLAUQEwPgDEeAzqXP4Aq1MyrpDgbVSodQZKtWkElVmJIgru3DNuWSwdkpGW/vbIyEdY6J1TpnXOrgC6l2/KSP86CSyj1vq0GexMU5hgHSvTeu9l7H33I4C%2Bl5bz1kgEkAc7ZBz4i7GHQcjQuxdgHMkHBWCByr27EwwOh5DG1lXrMKpp96mT2MdWGiOFYbJBAA%3D%3D), which allows me to try different compilers. Apparently, you are experiencing a compiler bug, which affects GCC 11. You could work around it by using another version; e.g. GCC 10 or GCC 12 for example, but this can be tricky to do. A much easier thing you can try is to apply system upgrades: I see you are running GCC 11.2, but 11.3 should be available in your system's updates. Although Compiler Explorer suggests that GCC 11.3 should also have the problem, when I tested it myself on a Docker container of Ubuntu 22.04, it worked fine.

When I have a moment, I will push a workaround that will allow you to compile with GCC 11.2.

**Comment by temuller** [comment] 2022-07-12 08:13
Thanks for you help!

**Comment by cschreib** [comment] 2022-07-12 19:11
If you are able to try the latest commit on the master branch, the problem should be fixed. Please let me know if that worked!

**Comment by temuller** [comment] 2022-07-13 06:27
@cschreib I re-installed it from scratch and it is now working. Thanks!

**Comment by cschreib** [comment] 2022-07-13 07:06
Closing as the problem is now resolved. Thank you for reporting it, and good luck with your fits!

**Closed as completed by cschreib** 2022-07-13 07:06 UTC
Labels: cannot compile, fixed in v1.3.2
