### ISSUE TITLE
valid dust laws

### ISSUE THREAD

**Issue by brojonat** [cschreib/fastpp#8] opened 2019-01-10 18:37 UTC
Running some initial tests and noticed an issue with the valid dust laws in fast++-read_input.cpp:
```
note: this is FAST++ version '1.2'
error: unknown dust law 'mw'
error: possible values: {calzetti, mz, noll, kc}
```

**Comment by cschreib** [comment] 2019-01-11 09:37
Thanks for reporting the bug! This should now be fixed on the master branch. Please let me know if the problem is not actually solved for you.

**Closed as completed by cschreib** 2019-01-11 09:37 UTC
Labels: bug, fixed in v1.2
