### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by themiyan** [cschreib/fastpp#2] opened 2018-06-14 12:58 UTC
when I try to install the code in strw desktops I get the following error:

is this a quick fix? 

[ 93%] Performing build step for 'fast++'
Scanning dependencies of target fast++-sfh2sed
[  7%] Building CXX object CMakeFiles/fast++-sfh2sed.dir/fast++-sfh2sed.cpp.o
/data2/themiya/softwares/fastpp/src/fast++-sfh2sed.cpp: In function ‘int phypp_main(int, char**)’:
/data2/themiya/softwares/fastpp/src/fast++-sfh2sed.cpp:58:9: error: ‘end_with’ was not declared in this scope
     if (end_with(sfh_file, ".fits")) {
         ^~~~~~~~
make[5]: *** [CMakeFiles/fast++-sfh2sed.dir/build.make:63: CMakeFiles/fast++-sfh2sed.dir/fast++-sfh2sed.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:68: CMakeFiles/fast++-sfh2sed.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/fast++.dir/build.make:113: fast++-prefix/src/fast++-stamp/fast++-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/fast++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
kuider [524] $

**Comment by themiyan** [comment] 2018-06-14 13:04
I should add the machines I tested (inclusing para33) had the system gcc
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

and in my laptop:
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0

I beleive this should be backword compatible with the compiler requirements?

**Comment by cschreib** [comment] 2018-06-14 14:32
Sorry, this is something i fixed on my local repository and forgot to update the code here. If you ``git pull`` and compile again the error should disappear. Let me know!

**Comment by themiyan** [comment] 2018-06-14 15:04
Great, thanks it install well now but there is another issue :) now there are 3 excutables! 

However, when fast++ is run it gives the following error but the same files work fine in the older version  ( commit 3e38a0805c6dbd32ae7566fe3eb0d74d1bcfb1b3 )

Maybe something else was also changed?


Themiyas-MacBook-Pro:udf themiya$ ../../bin/fast++ udf.param
note: this is FAST++ version '1.2'
note: using instantaneous SFRs
note: reading fluxes from 'udf.cat'
note: using column translation file 'udf.translate'
note: reading filters from '../muse_spec.FILTERS'
error: could not open filter file '../muse_spec.FILTERS'
Themiyas-MacBook-Pro:udf themiya$ ../../bin/fast++ udf.param
note: this is FAST++ version '1.2'
note: using instantaneous SFRs
note: reading fluxes from 'udf.cat'
note: using column translation file 'udf.translate'
note: reading filters from '../muse_spec.FILTERS'
note: found 10 filters in the database, will use 10 of them
note: reading fluxes...
note: fitting 1568 sources with 10 fluxes each
note: apply template library error function to photometry
warning: found 6 galaxies with z_spec lower than the minimum value of the grid (z < 0.01)
warning: will put them at z=0.01
warning: found 19 galaxies with z_spec lower than the minimum value of the grid (z < 0.01)
warning: will put them at z=0.01
note: define grid...
note: fitting a grid of 165044 templates (ntau=4,nmetal=1,nage=11,nav=31,nz=121)
note: cache file is 'bc03_pr_ch_exp_calzetti_f0376779c81231ec07e903c03de9fb844943a79b.grid'
error: unknown column ''
error: some of the requested columns do not exist, cannot proceed

**Comment by cschreib** [comment] 2018-06-14 15:16
Hmm. What is the value of the ``OUTPUT_COLUMNS`` parameter in your configuration file?

**Comment by themiyan** [comment] 2018-06-14 16:07
ah yes thanks. Stupid me. 
Seems the previous version by default generated all the columns when nothing was specified for that parameter.

Thanks all seems to work fine now and I will close this issue.

**Comment by cschreib** [comment] 2018-06-14 16:11
I'll add a check in the code to catch that specific mistake so next time it will tell you how to fix it :)

**Comment by themiyan** [comment] 2018-07-09 13:43
I'm not sure what has happened but the newer clones lack some files in the extrenal folder. So cmake complains that it cannot find the phyppconfig* files. 

It installs fine when external files are copied from an older build. 
Looking at the commits it seems you've stopped the installation trying to get updates from other git repos. Would you thing this is the issue? 

error:

CMake Error at CMakeLists.txt:84 (find_package):
  By not providing "Findphypp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "phypp", but
  CMake did not find one.

  Could not find a package configuration file provided by "phypp" with any of
  the following names:

    phyppConfig.cmake
    phypp-config.cmake

  Add the installation prefix of "phypp" to CMAKE_PREFIX_PATH or set
  "phypp_DIR" to a directory containing one of the above files.  If "phypp"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

**Comment by cschreib** [comment] 2018-07-12 11:14
Confirmed, looking into it.

**Comment by cschreib** [comment] 2018-07-12 11:32
Turns out the issue was the last commit where I "simplified" (=broke) the build system. It worked fine if you updated a previous installation, but broke down for freshly cloned repositories. I've reverted this faulty commit, now it should work OK!

**Comment by themiyan** [comment] 2018-07-13 17:04
yes it worked on the previous commit. 
However the current master clone in the master branch is still broken.

**Comment by cschreib** [comment] 2018-07-18 09:19
Oops indeed, I forgot to push the changes to github. Thanks for reporting!

**Comment by cschreib** [comment] 2018-08-28 17:00
Closing this since problem is solved!

**Closed as completed by cschreib** 2018-08-28 17:00 UTC
Labels: fixed in v1.2, cannot compile
