### ISSUE TITLE
Failed fit comparisons between fastpp FAST

### ISSUE THREAD

**Issue by themiyan** [cschreib/fastpp#10] opened 2019-01-15 09:22 UTC
There are several galaxies in fastpp which fail to give a reasonably good SED fit to the data. A couple of examples shown below:
![sed_xi_ion_912](https://user-images.githubusercontent.com/5274688/51170826-abab8980-18af-11e9-83c1-764a5ae2ebcb.png)
![sed_xi_ion_5576](https://user-images.githubusercontent.com/5274688/51170838-b403c480-18af-11e9-8257-1401bff9f576.png)

Fitting them using similar parameters in FAST (IDL):
![sed_xi_ion_912](https://user-images.githubusercontent.com/5274688/51170501-e6f98880-18ae-11e9-95b4-a9561274f59e.png)
![sed_xi_ion_5576](https://user-images.githubusercontent.com/5274688/51170510-eeb92d00-18ae-11e9-903b-a5ac26a31bb1.png)

Any idea what would cause these discrepancies? 

input/output files can be found here: https://www.dropbox.com/sh/otrjvvtfs9k87b4/AABF4qR6cqhFj2y_rq9wJ0UBa?dl=0

**Comment by cschreib** [comment] 2019-01-18 17:11
Could you give me the IDs of these sources so I can look them up in the catalog and dig into this?

Otherwise, it seems the first galaxy has some fluxes that are zero, around lambda=4000A. You might want to check these, make sure that they are correctly flagged in the input catalog with either a negative error, or written as "NaN". Note that FAST will automatically discard all the fluxes with value equal to -99, regardless of the uncertainty. But FAST++ will not, because -99 could in principle be a valid flux measurement.

**Comment by themiyan** [comment] 2019-01-21 07:08
I've added a file called `failed` to the dropbox link with the IDs of the fails. You can check the SEDs in the folder `FASTPP_SEDs_bc03` 
I re-ran the catalogue using `nan` for the -99s. The new outputs are in the `zf_cosmos_zspec_fastpp` folder.

**Comment by cschreib** [comment] 2019-01-26 18:54
Thanks. I identified the issue, and (again) this is caused by ```BEST_FROM_SIM=1```. In the output SED file, the code was picking the model with the smallest chi2 on the true photometry, but it was taking the normalization factor from the models in the MC simulations. This is now fixed in the master branch. Incidentally, when setting ```BEST_FROM_SIM=1```, the code will now output the "median model" of the simulations, instead of the one with the smallest chi2 on the original photometry. If you don't want that, then set ```BEST_FROM_SIM=0```.

If you still see problematic SEDs after this fix, please re-open this issue.

NB: To be honest, even though I thought at the time it was a good idea to add this option to the code, now I'm no longer sure. I think there are better ways to reach the same goals. If you tell me why you want to use this option, perhaps I can suggest improvements.

**Closed as completed by cschreib** 2019-01-26 18:54 UTC
Labels: bug, fixed in v1.2.1

**Comment by themiyan** [comment] 2019-02-09 15:49
great. thanks. This seems to have fixed the issue. 

For `BEST_FROM_SIM` one would naively expect this to be closer to the truth value. Anyways I'll stick with not using this option then.
